# -*- coding: utf-8 -*-
"""lab_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woT5rgrIEc2dse8oId7JWGU83429DZIn
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

print("Loading MovieLens 100k dataset...")
url = "http://files.grouplens.org/datasets/movielens/ml-100k/u.data"
try:
    ratings = pd.read_csv(url, sep='\t', names=['user_id', 'movie_id', 'rating', 'timestamp'])
    print(f"✓ Dataset loaded: {len(ratings)} ratings")
except Exception as e:
    print(f"Warning: Could not load from URL: {e}")
    print("Using sample synthetic data instead...")
    np.random.seed(42)
    ratings = pd.DataFrame({
        'user_id': np.random.randint(1, 101, 10000),
        'movie_id': np.random.randint(1, 1001, 10000),
        'rating': np.random.choice([1, 2, 3, 4, 5], 10000),
        'timestamp': np.arange(10000)
    })

print("\n✓ Creating user-movie rating matrix...")
user_movie_matrix = ratings.pivot(index='user_id', columns='movie_id', values='rating').fillna(0)
R_matrix = user_movie_matrix.values

print(f"Matrix shape: {R_matrix.shape} ({R_matrix.shape[0]} users, {R_matrix.shape[1]} movies)")
print("\nSample of user-movie rating matrix (first 10 users and movies):")
print(user_movie_matrix.iloc[:10, :10])

from scipy.sparse.linalg import svds

print("\n✓ Performing SVD decomposition (k=20)...")
U, sigma, Vt = svds(R_matrix, k=20)
sigma_diag = np.diag(sigma)
predicted_ratings = np.dot(np.dot(U, sigma_diag), Vt)

print(f"U matrix shape: {U.shape}")
print(f"Sigma values: {sigma}")
print(f"Vt matrix shape: {Vt.shape}")

print("\nU matrix (first 5 rows):")
print(U[:5])

print("\nSigma matrix (shape {}):".format(sigma_diag.shape))
print(sigma_diag)

print("\nVt matrix (first 5 rows):")
print(Vt[:5])

print("\n✓ Generating singular values plot...")
fig = plt.figure(figsize=(10, 5))
plt.plot(range(len(sigma)), sorted(sigma, reverse=True), marker='o', linestyle='-')
plt.title('Singular Values from SVD Decomposition')
plt.xlabel('Index')
plt.ylabel('Singular Value')
plt.grid(True, alpha=0.3)
fig.savefig('ml10_singular_values.png')
plt.close(fig)

from sklearn.metrics import mean_squared_error

print("\n✓ Computing RMSE...")
actual = R_matrix[R_matrix != 0]
predicted = predicted_ratings[R_matrix != 0]
rmse = np.sqrt(mean_squared_error(actual, predicted))
print(f'RMSE: {rmse:.4f}')

print("✓ Generating actual vs predicted plot...")
fig = plt.figure(figsize=(10, 6))
plt.scatter(actual, predicted, alpha=0.5, s=10)
plt.plot([actual.min(), actual.max()], [actual.min(), actual.max()], 'r--', lw=2, label='Perfect Prediction')
plt.title(f'Actual vs Predicted Ratings (RMSE: {rmse:.4f})')
plt.xlabel('Actual Rating')
plt.ylabel('Predicted Rating')
plt.legend()
plt.grid(True, alpha=0.3)
fig.savefig('ml10_actual_vs_predicted.png')
plt.close(fig)

print("✓ Generating recommendation heatmap...")
user_idx = 0
top_movies = np.argsort(predicted_ratings[user_idx])[-10:][::-1]

fig = plt.figure(figsize=(10, 4))
plt.bar(range(len(top_movies)), predicted_ratings[user_idx][top_movies])
plt.title(f'Top 10 Movie Recommendations for User {user_idx + 1}')
plt.xlabel('Movie Rank')
plt.ylabel('Predicted Rating')
plt.xticks(range(len(top_movies)), [f'M{top_movies[i]+1}' for i in range(len(top_movies))])
plt.grid(True, alpha=0.3, axis='y')
fig.savefig('ml10_top_recommendations.png')
plt.close(fig)

print("\n✓ All visualizations saved! Check: ml10_singular_values.png, ml10_actual_vs_predicted.png, ml10_top_recommendations.png")