# -*- coding: utf-8 -*-
"""lab_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggRigTY0IRzOz_E_HGT66-XLvgScqWAC
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset robustly with fallback
print("Loading wine quality dataset...")
df = None
try:
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
    df = pd.read_csv(url, sep=';')
    print(f"Dataset loaded: {len(df)} samples")
except Exception as e:
    print(f"Warning: Could not load from URL: {e}")
    print("Creating synthetic wine quality dataset for demo...")
    np.random.seed(42)
    df = pd.DataFrame({
        'fixed acidity': np.random.uniform(4.6, 15.9, 1000),
        'volatile acidity': np.random.uniform(0.12, 1.58, 1000),
        'citric acid': np.random.uniform(0, 1, 1000),
        'residual sugar': np.random.uniform(0.9, 15.5, 1000),
        'chlorides': np.random.uniform(0.012, 0.611, 1000),
        'free sulfur dioxide': np.random.uniform(1, 72, 1000),
        'total sulfur dioxide': np.random.uniform(6, 289, 1000),
        'density': np.random.uniform(0.9901, 1.0037, 1000),
        'pH': np.random.uniform(2.74, 4.01, 1000),
        'sulphates': np.random.uniform(0.33, 2, 1000),
        'alcohol': np.random.uniform(8.4, 14.9, 1000),
        'quality': np.random.randint(3, 9, 1000)
    })
    print(f"Synthetic dataset created: {len(df)} samples")

# Display first few rows
print("\nDataset Preview:")
print(df.head())

# Check info
print("\nDataset Info:")
print(df.info())

# Extract features (X) and target (y)
X = df.drop('quality', axis=1)
y = df['quality']

print(f"\nFeature shape: {X.shape}")
print(f"Target shape: {y.shape}")

# Standardize features
print("\n✓ Standardizing features...")
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into training and testing sets
print("✓ Splitting data...")
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Apply PCA
print("✓ Applying PCA...")
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(f"Explained variance ratio: {pca.explained_variance_ratio_}")

print("✓ Training Random Forest classifier...")
rf_pca = RandomForestClassifier(random_state=42, n_jobs=-1)
rf_pca.fit(X_train_pca, y_train)

# Predictions
print("✓ Generating predictions...")
y_pred_pca = rf_pca.predict(X_test_pca)

print(f"\nAccuracy of Random Forest with PCA: {accuracy_score(y_test, y_pred_pca):.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_pca))

# Confusion Matrix visualization
print("✓ Generating confusion matrix plot...")
fig = plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred_pca)
sns.heatmap(cm, annot=True, cmap='Blues', fmt='g')
plt.title("Confusion Matrix - PCA Model")
plt.xlabel("Predicted")
plt.ylabel("Actual")
fig.savefig('ml6_confusion_matrix.png')
plt.close(fig)

# PCA scatter plot
print("✓ Generating PCA scatter plot...")
fig = plt.figure(figsize=(8, 6))
plt.scatter(X_train_pca[:, 0], X_train_pca[:, 1], c=y_train, cmap='viridis', alpha=0.7)
plt.title("PCA - Wine Dataset (2 Components)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label='Wine Quality')
fig.savefig('ml6_pca_scatter.png')
plt.close(fig)

print("\n✓ All visualizations saved! Check: ml6_confusion_matrix.png, ml6_pca_scatter.png")
