# -*- coding: utf-8 -*-
"""lab_8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2GQ37Npd52uJcHHBM45VM9Oc2tODvg0
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

# Load dataset robustly (works in local, CI, or container)
csv_candidates = [
    "Mall_Customers - Mall_Customers.csv",
    "Mall_Customers.csv",
    os.path.join("data", "Mall_Customers - Mall_Customers.csv"),
    os.path.join("data", "Mall_Customers.csv"),
]
csv_path = None
for p in csv_candidates:
    if os.path.exists(p):
        csv_path = p
        break

if csv_path:
    df = pd.read_csv(csv_path)
    print(f"Loaded dataset from: {csv_path}")
else:
    # If file isn't present, create a synthetic dataset with the expected columns
    print("Dataset file not found. Creating synthetic sample dataset for demo...")
    np.random.seed(42)
    df = pd.DataFrame({
        'CustomerID': np.arange(1, 201),
        'Gender': np.random.choice(['Male', 'Female'], 200),
        'Age': np.random.randint(18, 70, 200),
        'Annual Income (k$)': np.random.randint(15, 150, 200),
        'Spending Score (1-100)': np.random.randint(1, 100, 200)
    })
print(df.head())
print(df.info())

# Select relevant features for clustering
X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertia = []
K = range(1, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, init='k-means++', random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

fig = plt.figure(figsize=(8,5))
plt.plot(K, inertia, 'bo-')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
fig.savefig('ml8_elbow.png')
plt.close(fig)

# Apply K-Means with k=5
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
y_kmeans = kmeans.fit_predict(X_scaled)

# Add cluster labels to DataFrame
df['KMeans_Cluster'] = y_kmeans

fig = plt.figure(figsize=(8,6))
sax = sns.scatterplot(x=X_scaled[:,0], y=X_scaled[:,1], hue=y_kmeans, palette='viridis', s=80)
plt.title('Customer Segments using K-Means Clustering')
plt.xlabel('Annual Income (scaled)')
plt.ylabel('Spending Score (scaled)')
plt.legend(title='Cluster')
fig.savefig('ml8_kmeans.png')
plt.close(fig)

fig = plt.figure(figsize=(10,6))
linkage_matrix = linkage(X_scaled, method='ward')
dendrogram(linkage_matrix)
plt.title('Dendrogram for Hierarchical Clustering')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distance')
fig.savefig('ml8_dendrogram.png')
plt.close(fig)

# Apply Agglomerative Clustering with same number of clusters as K-Means
hc = AgglomerativeClustering(n_clusters=5, metric='euclidean', linkage='ward')
y_hc = hc.fit_predict(X_scaled)

# Add to DataFrame
df['Hierarchical_Cluster'] = y_hc

fig = plt.figure(figsize=(8,6))
sax = sns.scatterplot(x=X_scaled[:,0], y=X_scaled[:,1], hue=y_hc, palette='coolwarm', s=80)
plt.title('Customer Segments using Hierarchical Clustering')
plt.xlabel('Annual Income (scaled)')
plt.ylabel('Spending Score (scaled)')
plt.legend(title='Cluster')
fig.savefig('ml8_hierarchical.png')
plt.close(fig)

print("K-Means Cluster Distribution:")
print(df['KMeans_Cluster'].value_counts())

print("\nHierarchical Cluster Distribution:")
print(df['Hierarchical_Cluster'].value_counts())